export enum SubCategory {
  Soup,
  Salads,
  Starters,
  Pastas,
  Burger,
  Wagyu,
  SpecialSelection,
  BoneIn,
  Beef,
  Chicken,
  Lamb,
  Fish,
  Pork,
  Desserts,
  Sauces,
  Sides,
  Champagne,
  SparklingWine,
  RoseWine,
  WhiteWine,
  RedWine,
  ButcherFreshMeats,
  Souvenirs,
}

export const SUBCATEGORY_NAME = new Map<SubCategory, string>([
  [SubCategory.Soup, 'Soup'],
  [SubCategory.Salads, 'Salads'],
  [SubCategory.Starters, 'Starters'],
  [SubCategory.Pastas, 'Pastas'],
  [SubCategory.Burger, 'El Gaucho Burger'],
  [SubCategory.Wagyu, 'Wagyu'],
  [SubCategory.SpecialSelection, 'Special Selection'],
  [SubCategory.BoneIn, 'Bone-In'],
  [SubCategory.Beef, 'Beef'],
  [SubCategory.Chicken, 'Chicken'],
  [SubCategory.Lamb, 'Lamb'],
  [SubCategory.Fish, 'Fish'],
  [SubCategory.Pork, 'Pork'],
  [SubCategory.Desserts, 'Desserts'],
  [SubCategory.Sauces, 'Sauces'],
  [SubCategory.Sides, 'Sides'],
  [SubCategory.Champagne, 'Champagne'],
  [SubCategory.SparklingWine, 'Sparkling Wine'],
  [SubCategory.RoseWine, 'Rose’ Wine'],
  [SubCategory.WhiteWine, 'White Wine'],
  [SubCategory.RedWine, 'Red Wine'],
  [SubCategory.ButcherFreshMeats, 'El Butcher | Fresh Meats'],
  [SubCategory.Souvenirs, 'El Souvenirs'],
]);

export const SUBCATEGORIES: SubCategory[] = [
  SubCategory.Soup,
  SubCategory.Salads,
  SubCategory.Starters,
  SubCategory.Pastas,
  SubCategory.Burger,
  SubCategory.Wagyu,
  SubCategory.SpecialSelection,
  SubCategory.BoneIn,
  SubCategory.Beef,
  SubCategory.Chicken,
  SubCategory.Lamb,
  SubCategory.Fish,
  SubCategory.Pork,
  SubCategory.Desserts,
  SubCategory.Sauces,
  SubCategory.Sides,
  SubCategory.Champagne,
  SubCategory.SparklingWine,
  SubCategory.RoseWine,
  SubCategory.WhiteWine,
  SubCategory.RedWine,
  SubCategory.ButcherFreshMeats,
  SubCategory.Souvenirs,
];
